//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNet编辑器.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eNet编辑器.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        internal static string DevStateOff {
            get {
                return ResourceManager.GetString("DevStateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        internal static string DevStateOn {
            get {
                return ResourceManager.GetString("DevStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备： 的本地化字符串。
        /// </summary>
        internal static string lbTitleDevice {
            get {
                return ResourceManager.GetString("lbTitleDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象： 的本地化字符串。
        /// </summary>
        internal static string lbTitleObj {
            get {
                return ResourceManager.GetString("lbTitleObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑 的本地化字符串。
        /// </summary>
        internal static string Logic {
            get {
                return ResourceManager.GetString("Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Online {
            get {
                object obj = ResourceManager.GetObject("Online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OutLine {
            get {
                object obj = ResourceManager.GetObject("OutLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 面板 的本地化字符串。
        /// </summary>
        internal static string Panel {
            get {
                return ResourceManager.GetString("Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景 的本地化字符串。
        /// </summary>
        internal static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感应编组 的本地化字符串。
        /// </summary>
        internal static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eNet编辑器 -  的本地化字符串。
        /// </summary>
        internal static string SoftName {
            get {
                return ResourceManager.GetString("SoftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时 的本地化字符串。
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名称： 的本地化字符串。
        /// </summary>
        internal static string TxtShowDevName {
            get {
                return ResourceManager.GetString("TxtShowDevName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑名称： 的本地化字符串。
        /// </summary>
        internal static string TxtShowLogicName {
            get {
                return ResourceManager.GetString("TxtShowLogicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面板名称： 的本地化字符串。
        /// </summary>
        internal static string TxtShowPanelName {
            get {
                return ResourceManager.GetString("TxtShowPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景名称： 的本地化字符串。
        /// </summary>
        internal static string TxtShowScnName {
            get {
                return ResourceManager.GetString("TxtShowScnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感应编组名称： 的本地化字符串。
        /// </summary>
        internal static string TxtShowSensorName {
            get {
                return ResourceManager.GetString("TxtShowSensorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时名称： 的本地化字符串。
        /// </summary>
        internal static string TxtShowTimerName {
            get {
                return ResourceManager.GetString("TxtShowTimerName", resourceCulture);
            }
        }
    }
}
